import java.util.Scanner;

public class Hokim {

    // The ancient Greeks believed that there were four elements that everything was made up of: earth, water, air, and fire. This theory was suggested around 450 BC, and it was later supported and added to by Aristotle.

    public static void main(String[] args) {
        String entree;
        String yesOrNo;

        do {
            Scanner input = new Scanner(System.in);
            System.out.println("Which of this elements definition would you like to know? \n(Air, Wind, Rock, Ocean, Water, Fire, Volcano)\nPlease enter the element:");
            entree = input.nextLine().toLowerCase().trim();
            definitions(entree);
            System.out.println("Would you like to enter another element? Yes/No");
            yesOrNo = input.next().toLowerCase().trim();

            while (!(yesOrNo.equalsIgnoreCase("yes") || yesOrNo.equalsIgnoreCase("no"))) {
                System.out.println("Invalid input. Please enter again (yes/no):");
                yesOrNo = input.next().toLowerCase().trim();
            }

        } while (yesOrNo.equalsIgnoreCase("yes"));

    }

    public static void definitions(String userEntree) {

        switch (userEntree) {
            case "air" ->
                    System.out.println("\"Air was considered a “pure” element, but in fact the air that’s all around us is made up of a variety of gases: primarily nitrogen and oxygen, with almost 1% argon and even smaller amounts of carbon dioxide and other elements such as krypton and helium. The composition of air is just right for life on Earth, though.\"");

            case "wind" ->
                    System.out.println("\"Wind is the natural movement of air or other gases relative to a planet's surface. Winds occur on a range of scales, from thunderstorm flows lasting tens of minutes, to local breezes generated by heating of land surfaces and lasting a few hours, to global winds resulting from the difference in absorption of solar energy between the climate zones on Earth.\"");

            case "rock" ->
                    System.out.println("\"In geology, rock (or stone) is any naturally occurring solid mass or aggregate of minerals or mineraloid matter. It is categorized by the minerals included, its chemical composition, and the way in which it is formed. Rocks form the Earth's outer solid layer, the crust, and most of its interior, except for the liquid outer core and pockets of magma in the asthenosphere.\"");

            case "ocean" ->
                    System.out.println("\"The ocean is the body of salt water that covers ~70.8% of the Earth.[8] In English, the term ocean also refers to any of the large bodies of water into which the world ocean is conventionally divided.[9] Distinct names are used to identify five different areas of the ocean: Pacific, Atlantic, Indian, Antarctic/Southern, and Arctic.[10][11] The ocean contains 97% of Earth's water[8] and is the primary component of the Earth's hydrosphere, thus the ocean is essential to life on Earth.\"");

            case "water" ->
                    System.out.println("\"Water has many unique properties. The chemical formula of water is H20, meaning it is made of two hydrogen atoms bonded to one oxygen atom. The hydrogen atoms each attach to one side of the oxygen atom and have a positive charge whereas the oxygen atom has a negative charge. This polarizes the water molecule, much like a magnet, giving a water molecule positive and negative ends.\"");

            case "fire" ->
                    System.out.println("\"How does fire work? It’s closely linked to air. Fire needs three things in order to exist: oxygen, fuel, and heat.\nThe intensity of a fire varies because it is dependent on the oxygen, fuel, and heat available to it. When all three of these things are in a controlled situation, such as in candles or a campfire, fires are considered helpful. But when one or more of these things are not controlled, such as in a wildfire or a burning building, fires can easily become very dangerous.\"");

            case "volcano" ->
                    System.out.println("\"A volcano is a rupture in the crust of a planetary-mass object, such as Earth, that allows hot lava, volcanic ash, and gases to escape from a magma chamber below the surface.\"");

            default ->
                    System.out.println("Please enter one of these elements Air, Wind, Rock, Ocean, Water, Fire, Volcano");
        }
    }
}

